services:
  - type: web
    name: vendorbridge-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true

  - type: web
    name: vendorbridge-frontend
    env: node
    plan: starter
    rootDir: Frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
