// ============================================
// PDF Generation Service (PDFKit)
// ============================================
// Why: Purchase orders and invoices need professional
// PDF exports. PDFKit generates them server-side without
// browser dependencies. Branded headers, tables, totals.
// ============================================

const PDFDocument = require('pdfkit');

class PdfService {
  /**
   * Generate Purchase Order PDF
   * @returns {Promise<Buffer>}
   */
  static async generatePurchaseOrderPdf(po) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const buffers = [];

        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        // ── Header ──
        doc
          .fontSize(24)
          .fillColor('#667eea')
          .text('VendorBridge', { align: 'left' })
          .fontSize(10)
          .fillColor('#6b7280')
          .text('Intelligent Procurement & Vendor Management', { align: 'left' })
          .moveDown(0.5);

        doc
          .fontSize(18)
          .fillColor('#111827')
          .text('PURCHASE ORDER', { align: 'right' })
          .fontSize(12)
          .fillColor('#374151')
          .text(`PO #: ${po.poNumber}`, { align: 'right' })
          .text(`Date: ${new Date(po.createdAt).toLocaleDateString()}`, { align: 'right' })
          .text(`Status: ${po.status}`, { align: 'right' });

        doc.moveDown(1);
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e5e7eb');
        doc.moveDown(1);

        // ── Vendor Info ──
        doc
          .fontSize(12)
          .fillColor('#667eea')
          .text('VENDOR', { underline: true })
          .fontSize(10)
          .fillColor('#374151')
          .text(po.vendor?.companyName || 'N/A')
          .text(po.vendor?.contactPerson || '')
          .text(po.vendor?.email || '')
          .text(po.vendor?.phone || '');

        doc.moveDown(1);

        // ── Delivery Details ──
        if (po.deliveryDate || po.shippingAddress) {
          doc
            .fontSize(12)
            .fillColor('#667eea')
            .text('DELIVERY DETAILS', { underline: true })
            .fontSize(10)
            .fillColor('#374151');
          if (po.deliveryDate) doc.text(`Delivery Date: ${new Date(po.deliveryDate).toLocaleDateString()}`);
          if (po.shippingAddress) doc.text(`Ship To: ${po.shippingAddress}`);
          if (po.paymentTerms) doc.text(`Payment Terms: ${po.paymentTerms}`);
          doc.moveDown(1);
        }

        // ── Items Table ──
        doc
          .fontSize(12)
          .fillColor('#667eea')
          .text('ORDER ITEMS', { underline: true })
          .moveDown(0.5);

        // Table header
        const tableTop = doc.y;
        const colWidths = { item: 200, qty: 60, price: 100, total: 100 };

        doc
          .fontSize(9)
          .fillColor('#ffffff');

        // Header background
        doc
          .rect(50, tableTop, 495, 20)
          .fill('#667eea');

        doc
          .fillColor('#ffffff')
          .text('Item', 55, tableTop + 5, { width: colWidths.item })
          .text('Qty', 260, tableTop + 5, { width: colWidths.qty, align: 'center' })
          .text('Unit Price', 325, tableTop + 5, { width: colWidths.price, align: 'right' })
          .text('Total', 430, tableTop + 5, { width: colWidths.total, align: 'right' });

        // Table rows
        let rowY = tableTop + 25;
        const items = po.items || [];

        items.forEach((item, i) => {
          const bgColor = i % 2 === 0 ? '#f9fafb' : '#ffffff';
          doc.rect(50, rowY - 3, 495, 18).fill(bgColor);

          doc
            .fontSize(9)
            .fillColor('#374151')
            .text(item.itemName, 55, rowY, { width: colWidths.item })
            .text(String(item.quantity), 260, rowY, { width: colWidths.qty, align: 'center' })
            .text(`$${item.unitPrice.toFixed(2)}`, 325, rowY, { width: colWidths.price, align: 'right' })
            .text(`$${item.totalPrice.toFixed(2)}`, 430, rowY, { width: colWidths.total, align: 'right' });

          rowY += 20;
        });

        // Total
        doc.moveDown(1);
        doc
          .fontSize(14)
          .fillColor('#111827')
          .text(`Total: ${po.currency} $${po.totalAmount.toFixed(2)}`, { align: 'right' });

        // ── Notes ──
        if (po.notes) {
          doc.moveDown(1);
          doc
            .fontSize(10)
            .fillColor('#6b7280')
            .text('Notes:', { underline: true })
            .text(po.notes);
        }

        // ── Footer ──
        doc
          .fontSize(8)
          .fillColor('#9ca3af')
          .text(
            `Generated by VendorBridge ERP on ${new Date().toLocaleString()}`,
            50,
            doc.page.height - 50,
            { align: 'center' }
          );

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Generate Invoice PDF
   * @returns {Promise<Buffer>}
   */
  static async generateInvoicePdf(invoice) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const buffers = [];

        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        // ── Header ──
        doc
          .fontSize(24)
          .fillColor('#667eea')
          .text('VendorBridge', { align: 'left' })
          .fontSize(10)
          .fillColor('#6b7280')
          .text('Intelligent Procurement & Vendor Management', { align: 'left' })
          .moveDown(0.5);

        doc
          .fontSize(18)
          .fillColor('#111827')
          .text('INVOICE', { align: 'right' })
          .fontSize(12)
          .fillColor('#374151')
          .text(`Invoice #: ${invoice.invoiceNumber}`, { align: 'right' })
          .text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, { align: 'right' })
          .text(`PO #: ${invoice.purchaseOrder?.poNumber || 'N/A'}`, { align: 'right' })
          .text(`Status: ${invoice.status}`, { align: 'right' });

        doc.moveDown(1);
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e5e7eb');
        doc.moveDown(1);

        // ── Vendor Info ──
        doc
          .fontSize(12)
          .fillColor('#667eea')
          .text('FROM', { underline: true })
          .fontSize(10)
          .fillColor('#374151')
          .text(invoice.vendor?.companyName || 'N/A')
          .text(invoice.vendor?.email || '');

        doc.moveDown(1);

        // ── Items Table ──
        doc
          .fontSize(12)
          .fillColor('#667eea')
          .text('LINE ITEMS', { underline: true })
          .moveDown(0.5);

        const tableTop = doc.y;

        doc.rect(50, tableTop, 495, 20).fill('#667eea');

        doc
          .fontSize(9)
          .fillColor('#ffffff')
          .text('Description', 55, tableTop + 5, { width: 200 })
          .text('Qty', 260, tableTop + 5, { width: 60, align: 'center' })
          .text('Unit Price', 325, tableTop + 5, { width: 100, align: 'right' })
          .text('Total', 430, tableTop + 5, { width: 100, align: 'right' });

        let rowY = tableTop + 25;
        const items = invoice.items || [];

        items.forEach((item, i) => {
          const bgColor = i % 2 === 0 ? '#f9fafb' : '#ffffff';
          doc.rect(50, rowY - 3, 495, 18).fill(bgColor);

          doc
            .fontSize(9)
            .fillColor('#374151')
            .text(item.description, 55, rowY, { width: 200 })
            .text(String(item.quantity), 260, rowY, { width: 60, align: 'center' })
            .text(`$${item.unitPrice.toFixed(2)}`, 325, rowY, { width: 100, align: 'right' })
            .text(`$${item.totalPrice.toFixed(2)}`, 430, rowY, { width: 100, align: 'right' });

          rowY += 20;
        });

        // Totals
        doc.moveDown(1);
        doc.fontSize(10).fillColor('#374151');
        doc.text(`Subtotal: ${invoice.currency} $${invoice.totalAmount.toFixed(2)}`, { align: 'right' });
        doc.text(`Tax: ${invoice.currency} $${invoice.taxAmount.toFixed(2)}`, { align: 'right' });
        doc
          .fontSize(14)
          .fillColor('#111827')
          .text(`Grand Total: ${invoice.currency} $${invoice.grandTotal.toFixed(2)}`, { align: 'right' });

        if (invoice.dueDate) {
          doc
            .fontSize(10)
            .fillColor('#ef4444')
            .text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, { align: 'right' });
        }

        // Footer
        doc
          .fontSize(8)
          .fillColor('#9ca3af')
          .text(
            `Generated by VendorBridge ERP on ${new Date().toLocaleString()}`,
            50,
            doc.page.height - 50,
            { align: 'center' }
          );

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}

module.exports = PdfService;
